### ISSUE TITLE
separate main function

### ISSUE THREAD

**Issue by WebFreak001** [Manuzor/midltod-d#2]
If you put the main function into a separate file (`source/app.d`) people can use your tool as library inside of their D programs from the dub registry. Dub only includes `source/app.d` if compiling with configuration=application, which is the default. If you use midltod-d as a dependency in some other project it won't include the `app.d`.

**Comment by Manuzor** [comment]
Good point. Please see #3.

**Comment by Manuzor** [comment]
Has been resolved in #3.
